// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq6yujFreocLwi-EpjlWK0gP3fSNWUNFg',
    appId: '1:235492424157:web:135c4fe5b2cb1939bf9e34',
    messagingSenderId: '235492424157',
    projectId: 'eos-advanced',
    authDomain: 'eos-advanced.firebaseapp.com',
    storageBucket: 'eos-advanced.firebasestorage.app',
    measurementId: 'G-8TC6XB6M9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMC7MeUelzCQ-TRSoz7TtMaKBKa3A7Q8',
    appId: '1:235492424157:android:fc4d963c501f1b22bf9e34',
    messagingSenderId: '235492424157',
    projectId: 'eos-advanced',
    storageBucket: 'eos-advanced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuutznTiwzhh6mKukvHpaVpIDOtpYfQbY',
    appId: '1:235492424157:ios:ca66b5fc86dd39c5bf9e34',
    messagingSenderId: '235492424157',
    projectId: 'eos-advanced',
    storageBucket: 'eos-advanced.firebasestorage.app',
    androidClientId: '235492424157-n0u25p938m8isulhbkarl2km2ss2aq7i.apps.googleusercontent.com',
    iosClientId: '235492424157-e5ga1nhg737g35ls8v6sogatmkg84lqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.week02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq6yujFreocLwi-EpjlWK0gP3fSNWUNFg',
    appId: '1:235492424157:web:404e42a1edcaada3bf9e34',
    messagingSenderId: '235492424157',
    projectId: 'eos-advanced',
    authDomain: 'eos-advanced.firebaseapp.com',
    storageBucket: 'eos-advanced.firebasestorage.app',
    measurementId: 'G-EJBNFDML6G',
  );
}
